import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, onAuthStateChanged, signOut, setPersistence, inMemoryPersistence } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-auth.js';
import { getFirestore, doc, collection, getDoc, getDocs, setDoc, updateDoc, addDoc, query, where, orderBy, onSnapshot, runTransaction, serverTimestamp, increment } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const firebaseApp = initializeApp({ apiKey:'AIzaSyDSGih4EfBz4yO97V3-atDUxywL7NkuL9Q', authDomain:'ploget-f2ca9.firebaseapp.com', projectId:'ploget-f2ca9', storageBucket:'ploget-f2ca9.firebasestorage.app', messagingSenderId:'668637351138', appId:'1:668637351138:web:b3acf4f1f7e26f0596e2bb' });
const auth = getAuth(firebaseApp), db = getFirestore(firebaseApp);
let me = null, myProfile = null, stopRooms = null;
const $ = s => document.querySelector(s);
const escape = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normal = s => s.trim().toLowerCase();
const pseudoEmail = id => `${normal(id)}@ploget.app`;
const now = () => Date.now();
const dateTime = (d,t) => new Date(`${d}T${t}`).getTime();
const statusText = s => ({recruiting:'모집 중',full:'모집 마감','attendance-check':'출석 확인 중',in_progress:'봉사 진행 중',followup:'후속활동 진행 중',completed:'완료',cancelled:'취소'}[s] || s);
const notice = text => { $('#notice').textContent = text; };
const msg = (id,text,error=false) => { const el=$(id); el.textContent=text; el.style.color=error?'#d43d3d':''; };

function modal(icon,label,title,description,html='') {
  $('#modalIcon').textContent=icon; $('#modalLabel').textContent=label; $('#modalTitle').textContent=title;
  $('#modalDescription').textContent=description; $('#modalInfo').innerHTML=html; $('#modalActions').innerHTML='';
  $('#activityModal').classList.add('open'); $('#activityModal').setAttribute('aria-hidden','false');
}
function closeModal(){ $('#activityModal').classList.remove('open'); $('#activityModal').setAttribute('aria-hidden','true'); }
function action(text, handler, secondary=false) { const b=document.createElement('button'); b.textContent=text; b.className=secondary?'secondary-action':'action-button'; b.onclick=handler; $('#modalActions').append(b); }
async function audit(kind, roomId, details={}) { if (!me) return; await setDoc(doc(collection(db,'auditLogs')), {kind,roomId:roomId||null,actorId:me.uid,details,createdAt:serverTimestamp()}); }
async function profile() { const ref=doc(db,'users',me.uid), s=await getDoc(ref); if(!s.exists()){const id=(me.email||'member').replace('@ploget.app','');myProfile={normalizedId:id,displayId:id,points:0,activeRoomId:null,hostedRoomId:null};await setDoc(ref,{...myProfile,createdAt:serverTimestamp()});}else myProfile=s.data(); return myProfile; }
async function clearExpiredPenalty(tx, userRef) {
  const pRef=doc(db,'penalties',me.uid), p=await tx.get(pRef);
  if (p.exists() && p.data().active) { if ((p.data().expiresAt||0)>now()) throw new Error(`5분 이용 제한 중입니다. ${Math.ceil((p.data().expiresAt-now())/60000)}분 후 다시 시도해 주세요.`); tx.update(pRef,{active:false,releasedAt:serverTimestamp()}); }
}

async function signUp(e) {
  e.preventDefault(); const f=new FormData(e.currentTarget), id=normal(f.get('id')), pw=f.get('password');
  if (!/^[a-z0-9_.-]{2,20}$/.test(id)) return msg('#signupMessage','아이디는 영문·숫자·._- 2~20자로 입력해 주세요.',true);
  if (pw.length < 6) return msg('#signupMessage','비밀번호는 6자 이상으로 입력해 주세요.',true);
  if (pw !== f.get('confirm')) return msg('#signupMessage','비밀번호 확인이 일치하지 않습니다.',true);
  try {
    // Auth 계정을 먼저 만든 뒤, 로그인된 UID로 usernames를 트랜잭션 생성합니다.
    // Firebase Auth의 정규화된 이메일도 같은 ID의 동시 가입을 한 번 더 차단합니다.
    const cred=await createUserWithEmailAndPassword(auth,pseudoEmail(id),pw);
    await runTransaction(db, async tx => { const u=doc(db,'usernames',id), existing=await tx.get(u); if(existing.exists() && existing.data().uid!==cred.user.uid) throw new Error('이미 사용 중인 아이디입니다.'); tx.set(u,{uid:cred.user.uid,normalizedId:id,createdAt:serverTimestamp()}); tx.set(doc(db,'users',cred.user.uid),{normalizedId:id,displayId:id,points:0,activeRoomId:null,hostedRoomId:null,createdAt:serverTimestamp()}); });
    msg('#signupMessage','회원가입이 완료되었습니다.');
  } catch(err) { const text=err.code==='auth/email-already-in-use'?'이미 가입된 아이디입니다.':err.code==='auth/weak-password'?'비밀번호는 6자 이상으로 입력해 주세요.':err.code==='permission-denied'?'회원 정보 저장 권한이 없습니다. 잠시 뒤 다시 시도해 주세요.':`회원가입에 실패했습니다: ${err.message}`; msg('#signupMessage',text,true); }
}
async function signIn(e) { e.preventDefault(); const f=new FormData(e.currentTarget); try { await signInWithEmailAndPassword(auth,pseudoEmail(f.get('id')),f.get('password')); } catch { msg('#loginMessage','가입된 아이디와 비밀번호를 확인해 주세요.',true); } }

async function createRoom(form) {
  const f=new FormData(form), title=f.get('title').trim(), start=dateTime(f.get('date'),f.get('start')), end=dateTime(f.get('date'),f.get('end')), deadline=dateTime(f.get('deadlineDate'),f.get('deadlineTime')), cap=Number(f.get('capacity'));
  if(!title||!f.get('place').trim()||!f.get('content').trim()) throw new Error('모임 이름, 소개, 장소를 모두 입력해 주세요.');
  if(start<=now()||end<=start||deadline>=start||cap<2) throw new Error('날짜·시간·마감·정원을 다시 확인해 주세요.');
  const roomRef=doc(collection(db,'rooms')), hostPart=doc(db,`rooms/${roomRef.id}/participants/${me.uid}`), attendance=doc(db,`rooms/${roomRef.id}/attendance/${me.uid}`), userRef=doc(db,'users',me.uid);
  await runTransaction(db,async tx=>{
    const user=await tx.get(userRef); if(!user.exists()) throw new Error('프로필을 불러오지 못했습니다. 다시 로그인해 주세요.');
    await clearExpiredPenalty(tx,userRef);
    if(user.data().hostedRoomId) { const old=await tx.get(doc(db,'rooms',user.data().hostedRoomId)); if(old.exists() && !['completed','cancelled'].includes(old.data().status)) throw new Error('이전 개최 모임이 끝난 뒤 새 모임을 만들 수 있습니다.'); }
    const data={title,content:f.get('content').trim(),place:f.get('place').trim(),volunteerDate:f.get('date'),startTime:f.get('start'),endTime:f.get('end'),startsAt:start,endsAt:end,deadlineAt:deadline,capacity:cap,participantCount:1,hostId:me.uid,hostName:myProfile.displayId,status:'recruiting',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};
    tx.set(roomRef,data); tx.set(hostPart,{userId:me.uid,displayId:myProfile.displayId,role:'host',status:'pending',hasJoinedBefore:true,joinedAt:serverTimestamp()}); tx.set(attendance,{userId:me.uid,status:'pending',updatedAt:serverTimestamp()}); tx.update(userRef,{hostedRoomId:roomRef.id,activeRoomId:roomRef.id});
  }); await audit('room-created',roomRef.id); closeModal(); notice('봉사 모임을 만들었습니다.');
}
async function joinRoom(roomId) {
  const rRef=doc(db,'rooms',roomId), pRef=doc(db,`rooms/${roomId}/participants/${me.uid}`), aRef=doc(db,`rooms/${roomId}/attendance/${me.uid}`), uRef=doc(db,'users',me.uid);
  try { await runTransaction(db,async tx=>{ const [r,u,p]=await Promise.all([tx.get(rRef),tx.get(uRef),tx.get(pRef)]); if(!r.exists()||!u.exists()) throw new Error('모임 정보를 찾을 수 없습니다.'); const room=r.data(), user=u.data(); await clearExpiredPenalty(tx,uRef); if(room.hostId===me.uid) throw new Error('방장은 자신의 모임에 참가할 수 없습니다.'); if(room.status!=='recruiting'||room.deadlineAt<=now()) throw new Error('모집 중인 모임이 아니거나 마감되었습니다.'); if(room.participantCount>=room.capacity) throw new Error('정원이 모두 찼습니다.'); if(p.exists()||user.joinedRoomHistory?.includes(roomId)) throw new Error('한 번 참가한 모임에는 다시 참가할 수 없습니다.'); if(user.activeRoomId) throw new Error('이미 다른 모임에 참여 중입니다.'); tx.set(pRef,{userId:me.uid,displayId:myProfile.displayId,role:'member',status:'pending',hasJoinedBefore:true,joinedAt:serverTimestamp()}); tx.set(aRef,{userId:me.uid,status:'pending',updatedAt:serverTimestamp()}); tx.update(rRef,{participantCount:increment(1),status:room.participantCount+1===room.capacity?'full':'recruiting',updatedAt:serverTimestamp()}); tx.update(uRef,{activeRoomId:roomId,joinedRoomHistory:[...(user.joinedRoomHistory||[]),roomId]}); }); await audit('room-joined',roomId); notice('모임 참가가 완료되었습니다.'); openVolunteer(); } catch(e){ alert(e.message); }
}
async function cancelJoin(roomId) { const rRef=doc(db,'rooms',roomId), pRef=doc(db,`rooms/${roomId}/participants/${me.uid}`), uRef=doc(db,'users',me.uid); try { await runTransaction(db,async tx=>{const [r,p,u]=await Promise.all([tx.get(rRef),tx.get(pRef),tx.get(uRef)]); if(!r.exists()||!p.exists())throw new Error('참가 정보를 찾을 수 없습니다.'); if(r.data().hostId===me.uid)throw new Error('방장은 모임 전체 취소를 이용해 주세요.'); if(r.data().startsAt<=now()||!['recruiting','full'].includes(r.data().status))throw new Error('봉사 시작 전 모집 중인 모임만 취소할 수 있습니다.'); if(p.data().status==='cancelled')throw new Error('이미 취소된 참가입니다.'); tx.update(pRef,{status:'cancelled',cancelledAt:serverTimestamp()}); tx.update(rRef,{participantCount:increment(-1),status:'recruiting',updatedAt:serverTimestamp()}); tx.update(uRef,{activeRoomId:null}); }); await audit('join-cancelled',roomId); openVolunteer(); }catch(e){alert(e.message);} }

async function updateAttendance(roomId,userId,status,reason='') { const rRef=doc(db,'rooms',roomId), pRef=doc(db,`rooms/${roomId}/participants/${userId}`), aRef=doc(db,`rooms/${roomId}/attendance/${userId}`), penalty=doc(db,'penalties',userId); try { await runTransaction(db,async tx=>{const [r,p]=await Promise.all([tx.get(rRef),tx.get(pRef)]); if(!r.exists()||r.data().hostId!==me.uid||!['full','recruiting','attendance-check'].includes(r.data().status))throw new Error('출석 확인을 할 수 없는 모임입니다.'); if(!p.exists()||p.data().status==='cancelled')throw new Error('취소된 참가자는 처리할 수 없습니다.'); const previous=p.data().status; tx.update(pRef,{status,previousStatus:previous,reason,statusUpdatedAt:serverTimestamp(),updatedBy:me.uid}); tx.set(aRef,{userId,status,reason,updatedAt:serverTimestamp(),updatedBy:me.uid},{merge:true}); if(status==='absent') tx.set(penalty,{reason:'봉사 당일 불참',roomId,active:true,startedAt:serverTimestamp(),expiresAt:now()+5*60*1000}); }); await audit(`attendance-${status}`,roomId,{target:userId,reason}); openManage(roomId); }catch(e){alert(e.message);} }
async function undoExclusion(roomId,userId){const p=doc(db,`rooms/${roomId}/participants/${userId}`),a=doc(db,`rooms/${roomId}/attendance/${userId}`); await runTransaction(db,async tx=>{const r=await tx.get(doc(db,'rooms',roomId)), part=await tx.get(p); if(!r.exists()||r.data().hostId!==me.uid||!part.exists()||part.data().status!=='excluded'||r.data().startsAt<=now())throw new Error('되돌릴 수 없습니다.'); tx.update(p,{status:part.data().previousStatus||'pending',exclusionUndone:true});tx.set(a,{status:part.data().previousStatus||'pending',updatedAt:serverTimestamp()},{merge:true});});openManage(roomId);}
async function startRoom(roomId){try{await runTransaction(db,async tx=>{const rRef=doc(db,'rooms',roomId),r=await tx.get(rRef);if(!r.exists()||r.data().hostId!==me.uid)throw new Error('방장만 봉사를 시작할 수 있습니다.');const parts=await getDocs(collection(db,`rooms/${roomId}/participants`));const active=parts.docs.filter(x=>x.data().status!=='cancelled');if(active.some(x=>x.data().status==='pending'))throw new Error('모든 참가자의 출석 상태를 확인해 주세요.');if(!active.some(x=>x.data().status==='attended'))throw new Error('출석자가 한 명 이상 필요합니다.');if(['in_progress','followup','completed'].includes(r.data().status))throw new Error('이미 시작된 봉사입니다.');tx.update(rRef,{status:'in_progress',actualStartedAt:serverTimestamp(),updatedAt:serverTimestamp()});});await audit('room-started',roomId);openVolunteer();}catch(e){alert(e.message);}}
async function cancelRoom(roomId){if(!confirm('모임을 취소할까요? 기록은 남고 참가자에게 제재는 적용되지 않습니다.'))return;try{await runTransaction(db,async tx=>{const rRef=doc(db,'rooms',roomId),r=await tx.get(rRef);if(!r.exists()||r.data().hostId!==me.uid||r.data().startsAt<=now())throw new Error('봉사 시작 전 방장만 취소할 수 있습니다.');tx.update(rRef,{status:'cancelled',cancelledAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.update(doc(db,'users',me.uid),{hostedRoomId:null,activeRoomId:null});});await audit('room-cancelled',roomId);openVolunteer();}catch(e){alert(e.message);}}

async function submitFollowup(roomId){const rRef=doc(db,'rooms',roomId),pRef=doc(db,`rooms/${roomId}/participants/${me.uid}`),aRef=doc(db,`rooms/${roomId}/attendance/${me.uid}`),fRef=doc(db,`rooms/${roomId}/followups/${me.uid}`),cRef=doc(db,`rooms/${roomId}/pointClaims/${me.uid}`),uRef=doc(db,'users',me.uid);try{await runTransaction(db,async tx=>{const [r,p,a,f,c,u]=await Promise.all([tx.get(rRef),tx.get(pRef),tx.get(aRef),tx.get(fRef),tx.get(cRef),tx.get(uRef)]);if(!r.exists()||!p.exists()||p.data().status!=='attended'||!a.exists()||a.data().status!=='attended')throw new Error('출석 완료한 참가자만 후속활동을 제출할 수 있습니다.');if(!['in_progress','followup'].includes(r.data().status))throw new Error('봉사 진행 후에 인증할 수 있습니다.');if(f.exists()||c.exists())throw new Error('이미 후속활동과 포인트 지급이 완료되었습니다.');
      // SERVER TRANSITION NEEDED: Spark 클라이언트는 악의적 포인트 조작을 완전히 차단할 수 없어 향후 callable Cloud Function으로 이동해야 합니다.
      tx.set(fRef,{userId:me.uid,submittedAt:serverTimestamp(),method:'gps-photo',status:'approved'});tx.set(cRef,{userId:me.uid,points:500,claimedAt:serverTimestamp()});tx.update(uRef,{points:increment(500),activeRoomId:null,lastPointRoomId:roomId});tx.update(rRef,{status:'followup',updatedAt:serverTimestamp()});});await audit('followup-submitted',roomId);localStorage.setItem('ploget-volunteer-days',JSON.stringify([...(JSON.parse(localStorage.getItem('ploget-volunteer-days')||'[]')),new Date().toISOString().slice(0,10)]));alert('후속활동이 인증되어 500포인트가 지급되었습니다.');closeModal();}catch(e){alert(e.message);}}

async function openVolunteer(){ if(!me)return; const q=query(collection(db,'rooms'),orderBy('createdAt','desc')); const snaps=await getDocs(q); const rooms=snaps.docs.map(d=>({id:d.id,...d.data()})); modal('🗑','BEACH VOLUNTEER','봉사참여','모임을 만들거나 모집 중인 모임에 참여하세요.',`<div class="meeting-list"><button id="createRoom" class="action-button">봉사활동 개최</button><button id="myRooms" class="secondary-action">내 모임·참가 현황 보기</button>${rooms.filter(r=>!['cancelled','completed'].includes(r.status)).map(r=>`<div class="meeting"><span><strong>${escape(r.title)}</strong><small>${escape(r.place)} · ${r.volunteerDate} ${r.startTime}~${r.endTime}</small><small>${statusText(r.status)} · ${r.participantCount}/${r.capacity}명</small></span><b>${r.hostName}</b><button data-join="${r.id}" ${r.status!=='recruiting'||r.deadlineAt<now()?'disabled':''}>참가</button></div>`).join('')||'<p class="empty-groups">현재 모집 중인 모임이 없습니다.</p>'}</div>`); $('#createRoom').onclick=openCreate; $('#myRooms').onclick=openMyRooms; document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.join)); }
function openCreate(){const dt=new Date(Date.now()+3600000);const d=dt.toISOString().slice(0,10),t=dt.toTimeString().slice(0,5);modal('🌊','CREATE VOLUNTEER','봉사활동 개최','모든 시간은 광안리 현지 시간 기준입니다.',`<form id="roomForm" class="meet-form"><label>모임 이름<input name="title" required maxlength="40"></label><label>모임 소개<textarea name="content" required></textarea></label><label>장소<input name="place" required value="광안리 해변"></label><label>봉사 날짜<input name="date" type="date" required min="${d}"></label><label>시작 시간<input name="start" type="time" required value="${t}"></label><label>종료 시간<input name="end" type="time" required></label><label>모집 마감 날짜<input name="deadlineDate" type="date" required min="${d}"></label><label>모집 마감 시간<input name="deadlineTime" type="time" required></label><label>정원 (방장 포함)<input name="capacity" type="number" min="2" max="30" value="2" required></label><button class="action-button">모임 만들기</button></form>`);$('#roomForm').onsubmit=async e=>{e.preventDefault();try{await createRoom(e.currentTarget);}catch(err){alert(err.message);}};}
async function openMyRooms(){const p=await profile();const out=[];if(p.hostedRoomId){const d=await getDoc(doc(db,'rooms',p.hostedRoomId));if(d.exists())out.push({id:d.id,...d.data(),mine:'host'});}if(p.activeRoomId&&p.activeRoomId!==p.hostedRoomId){const d=await getDoc(doc(db,'rooms',p.activeRoomId));if(d.exists())out.push({id:d.id,...d.data(),mine:'member'});}modal('📋','MY VOLUNTEER','내 모임·참가 현황','모임 상태와 남은 인원을 확인하세요.',`<div class="meeting-list">${out.map(r=>`<div class="managed-meeting"><div><b>${escape(r.title)}</b><small>${statusText(r.status)} · ${r.participantCount}/${r.capacity}명 · ${r.volunteerDate} ${r.startTime}</small></div><span>${r.mine==='host'?'방장':'참가자'}</span><div class="manage-actions">${r.mine==='host'?`<button data-manage="${r.id}">출석·봉사 관리</button><button data-cancel-room="${r.id}">모임 취소</button>`:`<button data-cancel-join="${r.id}">참여 취소</button>`}</div></div>`).join('')||'<p class="empty-groups">현재 진행 중인 내 모임이 없습니다.</p>'}</div>`);document.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>openManage(b.dataset.manage));document.querySelectorAll('[data-cancel-room]').forEach(b=>b.onclick=()=>cancelRoom(b.dataset.cancelRoom));document.querySelectorAll('[data-cancel-join]').forEach(b=>b.onclick=()=>cancelJoin(b.dataset.cancelJoin));}
async function openManage(roomId){const r=(await getDoc(doc(db,'rooms',roomId))).data(), parts=(await getDocs(collection(db,`rooms/${roomId}/participants`))).docs.map(x=>x.data());modal('✅','ATTENDANCE','출석·봉사 관리',`${r.title} · ${statusText(r.status)}`,`<div class="meeting-list">${parts.map(p=>`<div class="managed-meeting"><div><b>${escape(p.displayId)} ${p.role==='host'?'(방장)':''}</b><small>현재 상태: ${p.status}</small></div><span>${p.status}</span>${p.status==='pending'?`<div class="manage-actions"><button data-attend="${p.userId}">참석</button><button data-absent="${p.userId}">불참</button><button data-exclude="${p.userId}">제외</button></div>`:p.status==='excluded'?`<button data-undo="${p.userId}" class="secondary-action">제외 되돌리기</button>`:''}</div>`).join('')}</div>`);action('봉사 실행하기',()=>startRoom(roomId));document.querySelectorAll('[data-attend]').forEach(b=>b.onclick=()=>updateAttendance(roomId,b.dataset.attend,'attended'));document.querySelectorAll('[data-absent]').forEach(b=>b.onclick=()=>updateAttendance(roomId,b.dataset.absent,'absent'));document.querySelectorAll('[data-exclude]').forEach(b=>b.onclick=()=>{const reason=prompt('제외 사유를 입력해 주세요.');if(reason&&confirm('정말 제외 처리할까요?'))updateAttendance(roomId,b.dataset.exclude,'excluded',reason);});document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>undoExclusion(roomId,b.dataset.undo));}
async function openFollowup(){const p=await profile();if(!p.activeRoomId)return alert('진행 중인 봉사 모임이 없습니다.');const r=await getDoc(doc(db,'rooms',p.activeRoomId));if(!r.exists())return alert('모임 정보를 찾을 수 없습니다.');modal('⌁','GPS & PHOTO','후속활동','출석 완료 후 GPS 1km와 인증 사진을 확인합니다.',`<div class="gps-proof"><b>${escape(r.data().title)}</b><strong>GPS 0.00 km</strong><p>1시간 안에 1km 이상 이동한 뒤 사진을 인증해 주세요.</p><div><button class="camera-button">GPS 시작</button><button class="camera-button">사진 촬영</button></div></div>`);action('후속활동 제출 · 500P',()=>submitFollowup(p.activeRoomId));}
async function openPoints(){const p=await profile();modal('P','MY POINTS','포인트 조회','후속활동 인증을 완료하면 포인트가 지급됩니다.',`<div class="points-board"><small>보유 포인트</small><strong>${Number(p.points||0).toLocaleString()} P</strong><span>10L 수거 인증 기준 500P</span></div>`);}
function openWeather(){modal('☀','GWANGALLI WEATHER','광안리 기상상황','안전한 봉사활동을 위해 출발 전 최신 기상 정보를 확인해 주세요.',`<div class="weather-now"><span>☀</span><div><b>광안리 해변</b><strong>맑음 24°</strong><small>미세먼지 좋음 · 파고 낮음</small></div></div><p class="weather-tip">날씨 정보는 안내용 예시입니다. 실제 출발 전 기상청 정보를 확인해 주세요.</p>`);}
function renderCalendar(){const m=new Date(), y=m.getFullYear(),mo=m.getMonth(),done=JSON.parse(localStorage.getItem('ploget-volunteer-days')||'[]');$('#calendarMonth').textContent=`${y}.${String(mo+1).padStart(2,'0')} 봉사 달력`;$('#calendarDays').innerHTML='<span></span>'.repeat(new Date(y,mo,1).getDay())+Array.from({length:new Date(y,mo+1,0).getDate()},(_,i)=>{const d=i+1,key=`${y}-${String(mo+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;return `<span class="${done.includes(key)?'done':''}">${d}</span>`}).join('');}
function bind(){ $('#showSignup').onclick=()=>{$('#startLoginForm').classList.add('hidden');$('#signupForm').classList.remove('hidden');};$('#showLogin').onclick=()=>{$('#signupForm').classList.add('hidden');$('#startLoginForm').classList.remove('hidden');};$('#startLoginForm').onsubmit=signIn;$('#signupForm').onsubmit=signUp;$('.close').onclick=closeModal;$('#activityModal').onclick=e=>{if(e.target===$('#activityModal'))closeModal();};document.querySelectorAll('.menu-card').forEach(b=>b.onclick=()=>({봉사참여:openVolunteer,후속활동:openFollowup,기상상황:openWeather,포인트조회:openPoints}[b.dataset.name]()));}
bind();$('#logoutButton').onclick=async()=>{await signOut(auth);closeModal();notice('로그아웃되었습니다.');};renderCalendar();await setPersistence(auth,inMemoryPersistence);await signOut(auth);onAuthStateChanged(auth,async user=>{me=user;if(!user){$('#logoutButton').classList.add('hidden');$('#startLogin').classList.remove('hidden');return;}await profile();$('#logoutButton').classList.remove('hidden');$('#startLogin').classList.add('hidden');notice(`${myProfile?.displayId||'회원'}님, 플로겟에 오신 것을 환영해요.`);});
